#!/bin/bash

log_name=duckdb_$1_$2_${i}.txt

rm -rf duckdb_$1_$2_*
rm -rf job_result/duckdb_$1_$2_*

hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/10a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/10b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/10c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/11a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/11b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/11c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/11d.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/12a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/12b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/12c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/13a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/13b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/13c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/13d.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/14a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/14b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/14c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/15a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/15b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/15c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/15d.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/16a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/16b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/16c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/16d.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/17a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/17b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/17c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/17d.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/17e.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/17f.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/18a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/18b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/18c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/19a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/19b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/19c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/19d.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/1a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/1b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/1c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/1d.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/20a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/20b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/20c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/21a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/21b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/21c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/22a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/22b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/22c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/22d.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/23a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/23b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/23c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/24a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/24b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/25a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/25b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/25c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/26a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/26b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/26c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/27a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/27b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/27c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/28a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/28b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/28c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/29a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/29b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/29c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/2a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/2b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/2c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/2d.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/30a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/30b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/30c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/31a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/31b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/31c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/32a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/32b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/33a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/33b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/33c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/3a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/3b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/3c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/4a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/4b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/4c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/5a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/5b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/5c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/6a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/6b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/6c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/6d.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/6e.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/6f.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/7a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/7b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/7c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/8a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/8b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/8c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/8d.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/9a.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/9b.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/9c.sql\" ./imdb.db" 2>&1|tee -a ${log_name}
hyperfine --warmup 10 "duckdb -c \".read /home/pei/Project/benchmarks/imdb_job-postgres/skinnerdb_queries/9d.sql\" ./imdb.db" 2>&1|tee -a ${log_name}


mv duckdb_$1_$2_* job_result/.
