queries="
.timer on
.read $JOB_PATH/skinnerdb_queries/10a.sql
.read $JOB_PATH/skinnerdb_queries/10b.sql
.read $JOB_PATH/skinnerdb_queries/10c.sql
.read $JOB_PATH/skinnerdb_queries/11a.sql
.read $JOB_PATH/skinnerdb_queries/11b.sql
.read $JOB_PATH/skinnerdb_queries/11c.sql
.read $JOB_PATH/skinnerdb_queries/11d.sql
.read $JOB_PATH/skinnerdb_queries/12a.sql
.read $JOB_PATH/skinnerdb_queries/12b.sql
.read $JOB_PATH/skinnerdb_queries/12c.sql
.read $JOB_PATH/skinnerdb_queries/13a.sql
.read $JOB_PATH/skinnerdb_queries/13b.sql
.read $JOB_PATH/skinnerdb_queries/13c.sql
.read $JOB_PATH/skinnerdb_queries/13d.sql
.read $JOB_PATH/skinnerdb_queries/14a.sql
.read $JOB_PATH/skinnerdb_queries/14b.sql
.read $JOB_PATH/skinnerdb_queries/14c.sql
.read $JOB_PATH/skinnerdb_queries/15a.sql
.read $JOB_PATH/skinnerdb_queries/15b.sql
.read $JOB_PATH/skinnerdb_queries/15c.sql
.read $JOB_PATH/skinnerdb_queries/15d.sql
.read $JOB_PATH/skinnerdb_queries/16a.sql
.read $JOB_PATH/skinnerdb_queries/16b.sql
.read $JOB_PATH/skinnerdb_queries/16c.sql
.read $JOB_PATH/skinnerdb_queries/16d.sql
.read $JOB_PATH/skinnerdb_queries/17a.sql
.read $JOB_PATH/skinnerdb_queries/17b.sql
.read $JOB_PATH/skinnerdb_queries/17c.sql
.read $JOB_PATH/skinnerdb_queries/17d.sql
.read $JOB_PATH/skinnerdb_queries/17e.sql
.read $JOB_PATH/skinnerdb_queries/17f.sql
.read $JOB_PATH/skinnerdb_queries/18a.sql
.read $JOB_PATH/skinnerdb_queries/18b.sql
.read $JOB_PATH/skinnerdb_queries/18c.sql
.read $JOB_PATH/skinnerdb_queries/19a.sql
.read $JOB_PATH/skinnerdb_queries/19b.sql
.read $JOB_PATH/skinnerdb_queries/19c.sql
.read $JOB_PATH/skinnerdb_queries/19d.sql
.read $JOB_PATH/skinnerdb_queries/1a.sql
.read $JOB_PATH/skinnerdb_queries/1b.sql
.read $JOB_PATH/skinnerdb_queries/1c.sql
.read $JOB_PATH/skinnerdb_queries/1d.sql
.read $JOB_PATH/skinnerdb_queries/20a.sql
.read $JOB_PATH/skinnerdb_queries/20b.sql
.read $JOB_PATH/skinnerdb_queries/20c.sql
.read $JOB_PATH/skinnerdb_queries/21a.sql
.read $JOB_PATH/skinnerdb_queries/21b.sql
.read $JOB_PATH/skinnerdb_queries/21c.sql
.read $JOB_PATH/skinnerdb_queries/22a.sql
.read $JOB_PATH/skinnerdb_queries/22b.sql
.read $JOB_PATH/skinnerdb_queries/22c.sql
.read $JOB_PATH/skinnerdb_queries/22d.sql
.read $JOB_PATH/skinnerdb_queries/23a.sql
.read $JOB_PATH/skinnerdb_queries/23b.sql
.read $JOB_PATH/skinnerdb_queries/23c.sql
.read $JOB_PATH/skinnerdb_queries/24a.sql
.read $JOB_PATH/skinnerdb_queries/24b.sql
.read $JOB_PATH/skinnerdb_queries/25a.sql
.read $JOB_PATH/skinnerdb_queries/25b.sql
.read $JOB_PATH/skinnerdb_queries/25c.sql
.read $JOB_PATH/skinnerdb_queries/26a.sql
.read $JOB_PATH/skinnerdb_queries/26b.sql
.read $JOB_PATH/skinnerdb_queries/26c.sql
.read $JOB_PATH/skinnerdb_queries/27a.sql
.read $JOB_PATH/skinnerdb_queries/27b.sql
.read $JOB_PATH/skinnerdb_queries/27c.sql
.read $JOB_PATH/skinnerdb_queries/28a.sql
.read $JOB_PATH/skinnerdb_queries/28b.sql
.read $JOB_PATH/skinnerdb_queries/28c.sql
.read $JOB_PATH/skinnerdb_queries/29a.sql
.read $JOB_PATH/skinnerdb_queries/29b.sql
.read $JOB_PATH/skinnerdb_queries/29c.sql
.read $JOB_PATH/skinnerdb_queries/2a.sql
.read $JOB_PATH/skinnerdb_queries/2b.sql
.read $JOB_PATH/skinnerdb_queries/2c.sql
.read $JOB_PATH/skinnerdb_queries/2d.sql
.read $JOB_PATH/skinnerdb_queries/30a.sql
.read $JOB_PATH/skinnerdb_queries/30b.sql
.read $JOB_PATH/skinnerdb_queries/30c.sql
.read $JOB_PATH/skinnerdb_queries/31a.sql
.read $JOB_PATH/skinnerdb_queries/31b.sql
.read $JOB_PATH/skinnerdb_queries/31c.sql
.read $JOB_PATH/skinnerdb_queries/32a.sql
.read $JOB_PATH/skinnerdb_queries/32b.sql
.read $JOB_PATH/skinnerdb_queries/33a.sql
.read $JOB_PATH/skinnerdb_queries/33b.sql
.read $JOB_PATH/skinnerdb_queries/33c.sql
.read $JOB_PATH/skinnerdb_queries/3a.sql
.read $JOB_PATH/skinnerdb_queries/3b.sql
.read $JOB_PATH/skinnerdb_queries/3c.sql
.read $JOB_PATH/skinnerdb_queries/4a.sql
.read $JOB_PATH/skinnerdb_queries/4b.sql
.read $JOB_PATH/skinnerdb_queries/4c.sql
.read $JOB_PATH/skinnerdb_queries/5a.sql
.read $JOB_PATH/skinnerdb_queries/5b.sql
.read $JOB_PATH/skinnerdb_queries/5c.sql
.read $JOB_PATH/skinnerdb_queries/6a.sql
.read $JOB_PATH/skinnerdb_queries/6b.sql
.read $JOB_PATH/skinnerdb_queries/6c.sql
.read $JOB_PATH/skinnerdb_queries/6d.sql
.read $JOB_PATH/skinnerdb_queries/6e.sql
.read $JOB_PATH/skinnerdb_queries/6f.sql
.read $JOB_PATH/skinnerdb_queries/7a.sql
.read $JOB_PATH/skinnerdb_queries/7b.sql
.read $JOB_PATH/skinnerdb_queries/7c.sql
.read $JOB_PATH/skinnerdb_queries/8a.sql
.read $JOB_PATH/skinnerdb_queries/8b.sql
.read $JOB_PATH/skinnerdb_queries/8c.sql
.read $JOB_PATH/skinnerdb_queries/8d.sql
.read $JOB_PATH/skinnerdb_queries/9a.sql
.read $JOB_PATH/skinnerdb_queries/9b.sql
.read $JOB_PATH/skinnerdb_queries/9c.sql
.read $JOB_PATH/skinnerdb_queries/9d.sql
"
i=1
echo -ne "${queries}" | duckdb ./imdb.db 2>&1|tee -a duckdb_query_split_imdb_${i}.txt;

mv duckdb_query_split_imdb_* job_result/.
